source 'https://rubygems.org'
#ruby '2.1.2'

# PostgreSQL driver
gem 'pg'
gem 'bcrypt'
# Sinatra driver
gem 'sinatra'
gem 'sinatra-contrib'

# Use Thin for our web server
gem 'thin'
# gem 'bootstrap-star-rating'
# activerecord ORM
gem 'activesupport'
gem 'activerecord'
gem 'httparty'

#face recognition

gem 'yelp'
gem 'rake'
gem 'rack-flash3'
gem 'factory_girl'

group :test do
  gem 'shoulda-matchers'
  gem 'rack-test'
  gem 'capybara'
  gem 'selenium-webdriver'
end

group :test, :development do
  gem 'debugger'
  gem 'shotgun'
  gem 'dotenv-rails'
  gem 'rspec'
  gem 'faker'
end

